import "dotenv/config"; import { prisma } from "../db/prisma.js";
const raw = async <T=any>(s:string,...p:unknown[]):Promise<T[]>=>(await prisma.$queryRawUnsafe(s,...p)) as T[];
const [c]:any = await raw(`SELECT string_agg(column_name,', ' ORDER BY ordinal_position) c FROM information_schema.columns WHERE table_name='jobs'`);
console.log(`jobs columns: ${c.c}\n`);
const js = await raw(`SELECT "type", count(*)::int n, max("created_at")::text last FROM jobs WHERE "created_at" > now() - interval '7 hours' GROUP BY 1 ORDER BY 2 DESC`);
console.log(`jobs created in the last 7h:`);
for (const j of js) console.log(`   ${String(j.type).padEnd(34)} ${String(j.n).padStart(4)}   last ${String(j.last).slice(0,19)}`);
const sc = js.filter((j:any)=>/score|rescore/i.test(String(j.type)));
console.log(`\n⇒ scoring/rescore jobs in that window: ${sc.length===0?"✓ 0 — none enqueued, none executed":"⚠ "+JSON.stringify(sc)}`);
await prisma.$disconnect();
