import "dotenv/config"; import { prisma } from "../db/prisma.js";
const raw = async <T=any>(s:string,...p:unknown[]):Promise<T[]>=>(await prisma.$queryRawUnsafe(s,...p)) as T[];
const [s]=await raw(`SELECT count(*)::int n, max("created_at")::text mx FROM score_snapshots`);
console.log(`score_snapshots: ${s.n} rows · newest ${String(s.mx).slice(0,19)}  (was 5035 before this stage)`);
const j=await raw(`SELECT "type",count(*)::int n FROM background_jobs WHERE "created_at" > now() - interval '5 hours' GROUP BY 1 ORDER BY 2 DESC`);
console.log(`background_jobs created in the last 5h: ${j.length?j.map((x:any)=>`${x.type}=${x.n}`).join("  "):"(none)"}`);
const sc=await raw(`SELECT count(*)::int n FROM background_jobs WHERE "type" LIKE '%score%' AND "created_at" > now() - interval '5 hours'`);
console.log(`scoring-type jobs in the last 5h: ${sc[0].n}  ${sc[0].n===0?"✓ NO SCORING":"⚠"}`);
const a=await raw(`SELECT count(*) FILTER (WHERE "is_active")::int act, count(*)::int all FROM stocks`);
console.log(`stocks: ${a[0].act} active / ${a[0].all} total`);
const c=await raw(`SELECT count(*)::int n FROM stocks WHERE "is_active" AND "industryType"::text IN ('non_financial','banking')`);
console.log(`active cohort (nf+banking): ${c[0].n}  ${c[0].n===439?"✓ 439":"⚠"}`);
await prisma.$disconnect();
