// ═══════════════════════════════════════════════════════════════════════════════════════════════════
// STAGE 8 — LOAD THE FILLED WORKBOOK BACK INTO THE DATABASE.
//
//   npx tsx src/scripts/stage8-workbook-load.ts                      # validate only — writes NOTHING
//   npx tsx src/scripts/stage8-workbook-load.ts --apply              # write
//   npx tsx src/scripts/stage8-workbook-load.ts --only quarterly_results
//   npx tsx src/scripts/stage8-workbook-load.ts --dir X --verbose
//
// ── THE GUARANTEES ───────────────────────────────────────────────────────────────────────────────
//  1. IT NEVER OVERWRITES. A row that exists is filled ONLY where it is NULL, via
//     `SET col = COALESCE(col, $v)`. Automated data always wins over a hand-typed value, because the
//     automated path has a source URL and a parser that refused what it could not read.
//  2. IT NEVER WRITES AN EMPTY ROW. A row with no values is skipped, not inserted. An empty row
//     reads as complete to every consumer while occupying a retention slot — worse than the gap.
//  3. IT VALIDATES BEFORE IT WRITES. Unknown symbol, unparseable number, a column the table does not
//     have, a NOT NULL column with nothing to put in it, a fiscal-year label that contradicts its own
//     report date, a figure two orders of magnitude away from that company's own history — each is
//     REPORTED BY NAME and skipped. The run does not stop, so one bad cell cannot cost a session.
//  4. IT IS RE-RUNNABLE. Load a half-finished workbook as often as you like; already-present values
//     are left alone and reported as `unchanged`.
//
// Column names never reach SQL unchecked — every one is validated against information_schema first.
//
// ── WHAT THE FIRST REAL WORKBOOK TAUGHT THIS SCRIPT ──────────────────────────────────────────────
// Written against the schema in the abstract, it had six defects that only a filled workbook exposes.
// Each is now handled here, and each is worth naming because the next importer will meet them again:
//
//  A. ⚠ FISCAL-YEAR LABEL WIDTH. The workbook says `FY2025`; every table in this database stores
//     `FY25`, and that label is PART OF THE UNIQUE KEY. Loading it verbatim would have matched no
//     existing row (so every fill became an insert), created a parallel 4-digit universe alongside
//     the real one, and — worse — `decrementFY` in fiscal.ts matches /^FY(\d{2})$/ and THROWS on
//     anything else, so the poison would surface later, in scoring, far from its cause. Normalised
//     here, and cross-checked against the row's own report date.
//  B. `symbol` EXISTS ON ONE TABLE ONLY (shareholding_patterns). The rest key on stock_id alone.
//  C. `source` LIKEWISE DOES NOT EXIST on shareholding_patterns, and `updated_at` does not either.
//  D. SHAREHOLDING'S NATURAL KEY IS (stock_id, as_on_date) — that is the unique index. Matching on
//     (fiscal_year, quarter) is not the same thing: intra-quarter filings put two rows in one
//     quarter, so that key can resolve to the WRONG row, and an insert can hit the index instead.
//  E. total_shares / promoter_shares / pledged_shares are int8. A JS number is not a BigInt.
//  F. A UTF-8 BOM on the first header cell turns `symbol` into an unmatchable name, and every row
//     then fails with "unknown symbol" — a whole file lost to an invisible character.
// ═══════════════════════════════════════════════════════════════════════════════════════════════════
import "dotenv/config";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import crypto from "node:crypto";
import { prisma } from "../db/prisma.js";

// ── PRIMARY KEYS ARE GENERATED BY PRISMA, NOT BY POSTGRES ────────────────────────────────────────
// `id` is declared `@default(uuid())` or `@default(cuid())` in schema.prisma, and Prisma fills it in
// its own client layer — the COLUMN has no database default at all. Anything reaching these tables
// by raw SQL, as this loader does, must therefore supply the key itself or die on a NOT NULL
// violation. Which kind is per-model, so it is read out of schema.prisma rather than assumed: the
// tables in this workbook are not consistent with each other (shareholding_patterns is uuid, the
// financial tables are cuid), and writing the wrong shape would leave one table with two id formats.
/** table name -> "uuid" | "cuid", straight from the schema's own @default on the id field. */
function readIdKinds(): Map<string, "uuid" | "cuid"> {
  const out = new Map<string, "uuid" | "cuid">();
  const src = fs.readFileSync("prisma/schema.prisma", "utf8");
  for (const block of src.split(/\nmodel\s+/).slice(1)) {
    const map = /@@map\("([^"]+)"\)/.exec(block);
    const def = /\bid\s+String\s+@id\s+@default\((uuid|cuid)\(\)\)/.exec(block);
    if (map && def) out.set(map[1], def[1] as "uuid" | "cuid");
  }
  return out;
}
/** cuid v1: 'c' + time(base36) + counter + fingerprint + randomness = 25 chars, exactly the shape
 *  already in these tables. Reimplemented because Prisma does not export its generator. */
let cuidCount = Math.floor(Math.random() * 1679616);
const cuidFingerprint = (() => {
  const pid = process.pid.toString(36).padStart(2, "0").slice(-2);
  const host = os.hostname().split("").reduce((a, c) => a + c.charCodeAt(0), os.hostname().length + 36);
  return pid + host.toString(36).padStart(2, "0").slice(-2);
})();
const b36 = (n: number, w: number): string => Math.floor(n).toString(36).padStart(w, "0").slice(-w);
function cuid(): string {
  cuidCount = (cuidCount + 1) % 1679616;
  return `c${b36(Date.now(), 8)}${b36(cuidCount, 4)}${cuidFingerprint}${b36(Math.random() * 1679616, 4)}${b36(Math.random() * 1679616, 4)}`;
}

const argv = process.argv;
const APPLY = argv.includes("--apply");
const VERBOSE = argv.includes("--verbose");
const ONLY = argv.includes("--only") ? argv[argv.indexOf("--only") + 1] : null;
const DIR = argv.includes("--dir")
  ? argv[argv.indexOf("--dir") + 1]
  : ["WorkbookCompleted", "_WORKBOOK"].find((d) => fs.existsSync(d)) ?? "_WORKBOOK";

const raw = async <T = any>(s: string, ...p: unknown[]): Promise<T[]> => (await prisma.$queryRawUnsafe(s, ...p)) as T[];

const ANNUAL = new Set(["fundamentals", "banking_fundamentals", "nbfc_fundamentals", "life_insurance_fundamentals", "general_insurance_fundamentals"]);
const IDENTITY = new Set(["symbol", "isin", "company", "industry", "report_date", "as_on_date", "fiscal_year", "quarter", "result_type", "unit", "source_url", "notes"]);

/** Columns that scale with the company and never legitimately jump two orders of magnitude between
 *  adjacent years. The unit-error tripwire runs on these only — tax, capex and cash flow genuinely
 *  swing to near-zero and back, so a ratio test on them would cry wolf. */
const SCALE_COLS = new Set([
  "revenue", "expenses", "total_income", "total_expenses", "total_assets", "total_equity", "total_revenue",
  "interest_earned", "interest_expended", "deposits", "advances", "gross_premium_income", "gross_premiums_written",
  "premium_earned", "net_premium_written", "net_premium_income", "total_revenue_policyholders",
  "total_shares", "promoter_shares",
]);

// ── fiscal-year plumbing ─────────────────────────────────────────────────────────────────────────
/** `FY2025` | `FY25` | `2025` -> `FY25`. Anything else is refused rather than guessed at. */
function fyNorm(s: string): string | null {
  const t = s.trim().toUpperCase().replace(/\s/g, "");
  let m = /^FY?(\d{4})$/.exec(t) ?? /^(\d{4})$/.exec(t);
  if (m) return `FY${m[1].slice(-2)}`;
  m = /^FY(\d{2})$/.exec(t);
  return m ? `FY${m[1]}` : null;
}

// ⚠ NOT EVERY COMPANY'S YEAR ENDS IN MARCH, AND THE LABEL IS PART OF THE UNIQUE KEY.
//   The first live load derived labels from the Apr–Mar rule alone and wrote a neighbouring year's
//   figures into three rows before anything noticed:
//     · GILLETTE's year ends 30 JUNE. Its 2020-06-30 row is labelled FY20 in this database. The
//       workbook's 2019-06-30 row ALSO reduces to FY20 under Apr–Mar — so the key matched, and
//       FY2019's total_assets and total_equity were filled into FY2020's row.
//     · NESTLEIND (December year, pre-2023) and IFCI went the same way.
//     · Five December-year companies — CASTROLIND, CIEINDIA, CRISIL, HEXT, SCHAEFFLER — matched
//       their own Q4 (31 Dec) with a workbook row dated 31 March. Nothing was written only because
//       every column there was already populated. That is luck, not a safeguard.
//   So the year-end month is LEARNED FROM THE STOCK'S OWN ROWS, and the row is then located by its
//   DATE rather than by its label. A label is derived bookkeeping; the date is the identity.
/** Fiscal year-end for a company whose year ends in month `endMonth` (1-12). 2019-06-30 with a June
 *  year-end is FY19; 2025-03-31 with a March year-end is FY25; 2025-03-31 with a December year-end
 *  is FY25 Q1. In every convention this database uses, the label is the CALENDAR YEAR OF THE
 *  FISCAL YEAR-END — which is why the Apr–Mar shortcut works right up until it silently does not. */
function fyForConvention(d: Date, endMonth: number): { fy: string; quarter: string } {
  const y = d.getUTCFullYear(), mo = d.getUTCMonth() + 1;  // 1-12
  const endYear = mo <= endMonth ? y : y + 1;              // first year-end on/after d
  const startMonthAbs = endYear * 12 + endMonth - 11;      // first month of that fiscal year
  const idx = (y * 12 + mo) - startMonthAbs;               // 0..11
  return { fy: `FY${String(endYear % 100).padStart(2, "0")}`, quarter: `Q${Math.floor(idx / 3) + 1}` };
}

/** RFC4180-ish parser: quoted fields, doubled quotes, embedded commas and newlines. BOM-safe. */
function parseCsv(text: string): string[][] {
  if (text.charCodeAt(0) === 0xfeff) text = text.slice(1);   // defect F
  const rows: string[][] = [];
  let field = "", row: string[] = [], inQ = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQ) {
      if (c === '"') { if (text[i + 1] === '"') { field += '"'; i++; } else inQ = false; }
      else field += c;
    } else if (c === '"') inQ = true;
    else if (c === ",") { row.push(field); field = ""; }
    else if (c === "\n") { row.push(field); field = ""; rows.push(row); row = []; }
    else if (c !== "\r") field += c;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows.filter((r) => r.some((x) => x.trim() !== ""));
}

/** "1,234.5" | "(1234)" | "-1234" | "" -> number | null | NaN(=unparseable) */
function num(s: string): number | null | typeof NaN {
  const t = s.trim();
  if (t === "" || t === "-" || /^(na|n\/a|nil|null)$/i.test(t)) return null;
  const neg = /^\(.*\)$/.test(t);
  const cleaned = t.replace(/^\(|\)$/g, "").replace(/[,\s₹]/g, "");
  if (!/^-?\d*\.?\d+$/.test(cleaned)) return NaN;
  const v = Number(cleaned);
  return neg ? -v : v;
}

interface Stat { read: number; blank: number; invalid: number; inserted: number; filled: number; unchanged: number; cells: number }
const K: (keyof Stat)[] = ["read", "blank", "invalid", "inserted", "filled", "unchanged", "cells"];

async function main(): Promise<void> {
  if (!fs.existsSync(DIR)) { console.log(`no workbook directory at ${DIR}`); return; }
  const files = fs.readdirSync(DIR).filter((f) => f.endsWith(".csv") && !f.startsWith("_")).sort();
  console.log(`\n${"=".repeat(104)}`);
  console.log(`WORKBOOK LOAD ${APPLY ? "*** LIVE WRITE ***" : "(VALIDATE ONLY — nothing will be written)"}   ${DIR}  ${files.length} file(s)`);
  console.log("=".repeat(104));

  const stocks = new Map((await raw<{ id: string; symbol: string }>(`SELECT id, symbol FROM stocks`)).map((s) => [s.symbol.toUpperCase(), s.id]));
  const idKinds = readIdKinds();
  const problems: string[] = [];   // row was SKIPPED
  const warnings: string[] = [];   // row was loaded, but look at it
  const totals: Stat = { read: 0, blank: 0, invalid: 0, inserted: 0, filled: 0, unchanged: 0, cells: 0 };

  for (const file of files) {
    const table = file.replace(/\.csv$/, "");
    if (ONLY && table !== ONLY) continue;
    const rows = parseCsv(fs.readFileSync(path.join(DIR, file), "utf8"));
    if (rows.length < 2) { console.log(`\n  ${file}: header only, nothing to load`); continue; }

    // ── the table's real shape, so nothing unchecked reaches SQL ──────────────────────────────
    const schema = await raw<{ column_name: string; is_nullable: string; column_default: string | null; udt_name: string }>(
      `SELECT column_name, is_nullable, column_default, udt_name FROM information_schema.columns WHERE table_name=$1`, table);
    if (!schema.length) { problems.push(`${file}: no such table "${table}" — file ignored`); continue; }
    const known = new Set(schema.map((c) => c.column_name));
    const bigint = new Set(schema.filter((c) => c.udt_name === "int8").map((c) => c.column_name));   // defect E
    const notNull = schema.filter((c) => c.is_nullable === "NO" && !c.column_default && c.column_name !== "id").map((c) => c.column_name);

    const head = rows[0].map((h) => h.trim().replace(/^★/, ""));
    const dataCols = head.map((h, i) => ({ h, i })).filter((x) => !IDENTITY.has(x.h) && x.h !== "");
    const unknownCols = dataCols.filter((c) => !known.has(c.h)).map((c) => c.h);
    if (unknownCols.length) problems.push(`${file}: column(s) not on ${table}, ignored: ${unknownCols.join(", ")}`);
    const useCols = dataCols.filter((c) => known.has(c.h));
    const col = (name: string): number => head.indexOf(name);
    const isAnnual = ANNUAL.has(table);
    const isSh = table === "shareholding_patterns";
    const dateCol = isSh ? "as_on_date" : "report_date";
    const st: Stat = { read: 0, blank: 0, invalid: 0, inserted: 0, filled: 0, unchanged: 0, cells: 0 };

    // ── each stock's own fiscal-year-end month, read off its existing rows ────────────────────
    // For quarterly tables the tell is which month its Q4 lands in; for annual tables, the month its
    // year-end rows carry. A stock with no rows at all defaults to March, the Indian norm — and
    // since it has no rows, there is nothing for a wrong label to collide with.
    const fyEnd = new Map<string, number>();
    {
      const monthSql = isSh
        ? `SELECT DISTINCT stock_id, 3 AS m FROM shareholding_patterns WHERE false`
        : isAnnual
          ? `SELECT stock_id, mode() WITHIN GROUP (ORDER BY extract(month from report_date)::int) AS m FROM "${table}" GROUP BY 1`
          : `SELECT stock_id, mode() WITHIN GROUP (ORDER BY extract(month from report_date)::int) AS m FROM "${table}" WHERE quarter='Q4' GROUP BY 1`;
      for (const x of await raw<{ stock_id: string; m: number }>(monthSql)) fyEnd.set(x.stock_id, Number(x.m));
    }

    // ── each stock's own scale, for the unit tripwire ────────────────────────────────────────
    // ⚠ THE COMPARISON MUST BE LIKE FOR LIKE, OR IT BLOCKS GOOD DATA. The first version of this
    //   check took one median across the whole of a stock's history and refused 7 perfectly correct
    //   rows:
    //     · IIFL / MFSL / JMFINANCIL — a STANDALONE figure judged against a median dominated by
    //       CONSOLIDATED rows. A holding company's standalone revenue is two orders of magnitude
    //       below its consolidated revenue by construction; that is the correct number, not an error.
    //     · MMTC — revenue of ₹0.23 cr against a median of ₹1,170 cr. MMTC's trading business wound
    //       down; the database ALREADY holds 0.23 for that quarter. The median was the old era.
    //   So: same result_type, and the NEAREST periods in time rather than the whole series. A unit
    //   error stands out against its own neighbours; a business that genuinely changed size does not.
    const scaleCols = useCols.map((c) => c.h).filter((h) => SCALE_COLS.has(h));
    interface Obs { t: number; rt: string; v: number }
    const history = new Map<string, Record<string, Obs[]>>();
    if (scaleCols.length) {
      const hasRt = known.has("result_type");
      const syms = [...new Set(rows.slice(1).map((r) => (r[col("symbol")] ?? "").trim().toUpperCase()))];
      for (const s of syms) {
        const id = stocks.get(s);
        if (!id) continue;
        const past = await raw<Record<string, unknown>>(
          `SELECT "${dateCol}" AS _d${hasRt ? `, result_type::text AS _rt` : ""}, ${scaleCols.map((c) => `"${c}"`).join(",")}
             FROM "${table}" WHERE stock_id=$1`, id);
        const rec: Record<string, Obs[]> = {};
        for (const c of scaleCols) rec[c] = [];
        for (const p of past) {
          const t = new Date(p._d as string).getTime();
          const rt2 = hasRt ? String(p._rt ?? "") : "";
          for (const c of scaleCols) if (p[c] != null) rec[c].push({ t, rt: rt2, v: Number(p[c]) });
        }
        history.set(s, rec);
      }
    }
    /** The up-to-4 observations nearest in time, of the same basis. */
    const neighbours = (sym: string, c: string, when: number, rt2: string): number[] => {
      const obs = history.get(sym)?.[c];
      if (!obs) return [];
      return obs.filter((o) => o.rt === rt2 && Math.abs(o.t - when) > 0)
        .sort((a, b) => Math.abs(a.t - when) - Math.abs(b.t - when)).slice(0, 4)
        .map((o) => Math.abs(o.v)).filter((v) => v > 0);
    };
    /** ⚠ AGREEMENT WITH THE CLOSEST NEIGHBOUR, NOT WITH THEIR MEDIAN. A ₹lakh-for-₹crore slip is
     *  ~100x away from EVERY comparable period; a company whose scale genuinely changed still
     *  matches the periods on either side of the one being loaded. Taking a median instead refused
     *  MMTC's FY25 revenue of 2.69 — which sits exactly between FY24's 5.34 and FY26's 3.41 —
     *  because two rows from the pre-winddown era dragged the median to 138.9. Returns the ratio
     *  nearest to 1, or null when there is no like-for-like basis to judge against. */
    const scaleRatio = (sym: string, c: string, when: number, rt2: string, v: number): number | null => {
      const near = neighbours(sym, c, when, rt2);
      if (near.length < 1) return null;
      return near.map((m) => Math.abs(v) / m).reduce((a, b) => (Math.abs(Math.log(a)) <= Math.abs(Math.log(b)) ? a : b));
    };

    for (const r of rows.slice(1)) {
      st.read++;
      const at = `${file} row ${st.read}`;
      const sym = (r[col("symbol")] ?? "").trim().toUpperCase();
      const stockId = stocks.get(sym);
      if (!stockId) { st.invalid++; problems.push(`${at}: unknown symbol "${sym}"`); continue; }

      // ── identity, normalised and cross-checked against itself (defect A) ────────────────────
      const dateVal = (r[col(dateCol)] ?? "").trim();
      const fyRaw = (r[col("fiscal_year")] ?? "").trim();
      if (!fyRaw || !dateVal) { st.invalid++; problems.push(`${at} ${sym}: missing ${!fyRaw ? "fiscal_year" : dateCol}`); continue; }
      const dateObj = new Date(`${dateVal}T00:00:00.000Z`);
      if (Number.isNaN(dateObj.getTime())) { st.invalid++; problems.push(`${at} ${sym}: "${dateVal}" is not a date`); continue; }
      if (!fyNorm(fyRaw)) { st.invalid++; problems.push(`${at} ${sym}: fiscal_year "${fyRaw}" is not a label this database uses (FY25 / FY2025)`); continue; }
      const endMonth = fyEnd.get(stockId) ?? 3;
      const derived = fyForConvention(dateObj, endMonth);
      const fy = derived.fy;
      const q = isAnnual ? "" : derived.quarter;
      const stated = fyNorm(fyRaw)! + (isAnnual ? "" : (r[col("quarter")] ?? "").trim().toUpperCase());
      if (stated !== fy + q)
        warnings.push(`${at} ${sym} ${dateVal}: workbook says ${stated}, but this company's year ends in month ${endMonth}, so ${dateCol} ${dateVal} is ${fy}${q} here — loaded under ${fy}${q}, which is how the rest of its series is labelled`);
      const rt = isSh ? null : ((r[col("result_type")] ?? "standalone").trim().toLowerCase() || "standalone");
      if (rt && rt !== "standalone" && rt !== "consolidated") {
        st.invalid++; problems.push(`${at} ${sym}: result_type "${rt}" is neither standalone nor consolidated`); continue;
      }

      // ── the numbers ─────────────────────────────────────────────────────────────────────────
      const values: Record<string, number> = {};
      let bad = false;
      for (const c of useCols) {
        const v = num(r[c.i] ?? "");
        if (v === null) continue;
        if (Number.isNaN(v)) { bad = true; problems.push(`${at} ${sym} ${dateVal}: "${r[c.i]}" in ${c.h} is not a number`); continue; }
        values[c.h] = v as number;
      }
      if (bad) { st.invalid++; continue; }
      if (!Object.keys(values).length) { st.blank++; continue; }   // GUARANTEE 2

      // ── unit tripwire: ₹ lakh typed where ₹ crore was asked for is a 100x error ─────────────
      let unitError = false;
      for (const c of scaleCols) {
        const v = values[c];
        if (v == null || !v) continue;
        const ratio = scaleRatio(sym, c, dateObj.getTime(), rt ?? "", v);
        if (ratio == null) continue;                   // no like-for-like basis — say nothing
        const near = neighbours(sym, c, dateObj.getTime(), rt ?? "");
        if (ratio >= 50 || ratio <= 1 / 50) {
          unitError = true;
          problems.push(`${at} ${sym} ${dateVal}: ${c} = ${v} is ${ratio >= 50 ? `${ratio.toFixed(0)}x larger` : `${(1 / ratio).toFixed(0)}x smaller`} than EVERY neighbouring ${rt ?? "shareholding"} period (${near.join(", ")}) — reads as a unit error`);
        } else if (ratio >= 8 || ratio <= 1 / 8) {
          warnings.push(`${at} ${sym} ${dateVal}: ${c} = ${v}, closest neighbouring period is ${ratio >= 8 ? `${ratio.toFixed(1)}x` : `${(1 / ratio).toFixed(1)}x`} away (${near.join(", ")}) — loaded, but worth a look`);
        }
      }
      if (unitError) { st.invalid++; continue; }

      // ── accounting tells (reported, never blocking: minority interest and share of associates
      //    make the identity legitimately fail for a fifth of the rows this database already
      //    holds, so refusing on it would reject good data) ─────────────────────────────────────
      const V = (k: string): number | undefined => values[k];
      const pbt = V("profit_before_tax"), tax = V("tax"), np = V("net_profit");
      if (pbt != null && tax != null && np != null) {
        const d = Math.abs(pbt - tax - np);
        if (d > Math.max(1, Math.abs(pbt) * 0.02))
          warnings.push(`${at} ${sym} ${dateVal}: pbt(${pbt}) - tax(${tax}) != net_profit(${np}), off by ${d.toFixed(2)}`);
      }
      if (isSh) {
        const p = V("promoter_pct"), pub = V("public_pct"), ts = V("total_shares"), ps = V("promoter_shares"), pl = V("pledged_shares");
        if (p != null && pub != null && (p + pub < 98.5 || p + pub > 100.5))
          warnings.push(`${at} ${sym} ${dateVal}: promoter(${p}) + public(${pub}) = ${(p + pub).toFixed(2)}, not ~100`);
        if (ts != null && ps != null && ts > 0 && p != null && Math.abs((ps / ts) * 100 - p) > 0.6)
          warnings.push(`${at} ${sym} ${dateVal}: promoter_shares/total_shares = ${((ps / ts) * 100).toFixed(2)}% but promoter_pct = ${p}`);
        if (pl != null && ps != null && pl > ps)
          warnings.push(`${at} ${sym} ${dateVal}: pledged_shares(${pl}) exceeds promoter_shares(${ps})`);
        const fii = V("fii_pct"), dii = V("dii_pct");
        if (fii != null && dii != null && pub != null && fii + dii > pub + 0.05)
          warnings.push(`${at} ${sym} ${dateVal}: fii(${fii}) + dii(${dii}) exceeds public(${pub})`);
      }

      // ── locate the row BY ITS DATE (defect D, and the non-March-year defect above) ───────────
      // The date is what the workbook row actually is. The label is derived from it, so looking the
      // row up by label would let a labelling disagreement point at a different period's row — which
      // is exactly how three rows got a neighbouring year's figures on the first live run.
      const existing = await raw<{ id: string }>(
        isSh ? `SELECT id FROM "${table}" WHERE stock_id=$1 AND as_on_date=$2 LIMIT 1`
             : `SELECT id FROM "${table}" WHERE stock_id=$1 AND report_date=$2 AND result_type=$3 LIMIT 1`,
        ...(isSh ? [stockId, dateObj] : [stockId, dateObj, rt]));

      // ⚠ And before inserting: is the unique key already taken by a row of a DIFFERENT date? That
      //   is a label disagreement this loader must not resolve on its own — inserting would violate
      //   the index, and filling would put this period's figures into that period's row.
      if (!existing.length) {
        const clash = await raw<{ d: string }>(
          isSh ? `SELECT as_on_date::date::text AS d FROM "${table}" WHERE stock_id=$1 AND fiscal_year=$2 AND quarter=$3 LIMIT 1`
               : isAnnual
                 ? `SELECT report_date::date::text AS d FROM "${table}" WHERE stock_id=$1 AND fiscal_year=$2 AND result_type=$3 LIMIT 1`
                 : `SELECT report_date::date::text AS d FROM "${table}" WHERE stock_id=$1 AND fiscal_year=$2 AND quarter=$4 AND result_type=$3 LIMIT 1`,
          ...(isSh ? [stockId, fy, q] : isAnnual ? [stockId, fy, rt] : [stockId, fy, rt, q]));
        if (clash.length) {
          st.invalid++;
          problems.push(`${at} ${sym} ${dateVal}: ${fy}${q} ${rt ?? ""} is already held by the row dated ${clash[0].d}. Two different dates cannot share one label — this stock's fiscal-year labelling needs settling before the period can be loaded`);
          continue;
        }
      }

      const bind = (c: string, v: number): unknown => (bigint.has(c) ? BigInt(Math.round(v)) : v);

      if (existing.length) {
        // GUARANTEE 1 — fill NULLs only, never overwrite
        const cols = Object.keys(values);
        const before = await raw<Record<string, unknown>>(
          `SELECT ${cols.map((c) => `"${c}"`).join(",")} FROM "${table}" WHERE id=$1`, existing[0].id);
        const nullCols = cols.filter((c) => before[0][c] === null);
        if (!nullCols.length) { st.unchanged++; continue; }
        if (APPLY) {
          const sets = nullCols.map((c, i) => `"${c}" = COALESCE("${c}", $${i + 2})`);
          if (known.has("updated_at")) sets.push(`updated_at = now()`);          // defect C
          await prisma.$executeRawUnsafe(
            `UPDATE "${table}" SET ${sets.join(", ")} WHERE id = $1`,
            existing[0].id, ...nullCols.map((c) => bind(c, values[c])));
        }
        if (VERBOSE) console.log(`     fill  ${sym.padEnd(12)} ${dateVal} ${fy}${q}  ${nullCols.join(",")}`);
        st.filled++; st.cells += nullCols.length;
      } else {
        // ⚠ SYSTEM COLUMNS ARE SUPPLIED, NOT DEMANDED. These tables declare filing_date, xbrl_url,
        //   updated_at, source and (for shareholding) source_date NOT NULL with no default. Asking a
        //   person to type them would be asking for bookkeeping they cannot know; refusing the row
        //   because they are absent would reject perfectly good data. filing_date falls back to the
        //   report date — for a hand-entered row the true filing date is genuinely unknown, and "as
        //   at the period end" is the honest reading.
        //   Every one is gated on known.has(): only shareholding_patterns carries `symbol`, and it
        //   alone lacks `source` and `updated_at` (defects B and C).
        const idKind = idKinds.get(table);
        if (!idKind) { st.invalid++; problems.push(`${at}: schema.prisma declares no uuid()/cuid() id for ${table} — refusing to invent a primary key`); continue; }
        const id: Array<[string, unknown]> = [["id", idKind === "uuid" ? crypto.randomUUID() : cuid()], ["stock_id", stockId]];
        const put = (c: string, v: unknown): void => { if (known.has(c) && !(c in values)) id.push([c, v]); };
        put("symbol", sym);
        put("fiscal_year", fy);
        put(dateCol, dateObj);
        if (!isAnnual) put("quarter", q);
        if (!isSh) put("result_type", rt);
        put("source", "manual_workbook");
        put("filing_date", dateObj);
        put("xbrl_url", (r[col("source_url")] ?? "").trim());
        put("source_date", dateObj);
        put("updated_at", new Date());

        const covered = new Set([...id.map(([c]) => c), ...Object.keys(values)]);
        const missingRequired = notNull.filter((c) => !covered.has(c));
        if (missingRequired.length) {
          st.invalid++;
          problems.push(`${at} ${sym} ${dateVal}: cannot insert — ${table} requires ${missingRequired.join(", ")}, and the workbook leaves ${missingRequired.length > 1 ? "them" : "it"} blank`);
          continue;
        }
        const cols = [...id.map(([c]) => c), ...Object.keys(values)];
        const vals = [...id.map(([, v]) => v), ...Object.entries(values).map(([c, v]) => bind(c, v))];
        if (APPLY)
          await prisma.$executeRawUnsafe(
            `INSERT INTO "${table}" (${cols.map((c) => `"${c}"`).join(",")}) VALUES (${vals.map((_, i) => `$${i + 1}`).join(",")})`,
            ...vals);
        if (VERBOSE) console.log(`     NEW   ${sym.padEnd(12)} ${dateVal} ${fy}${q}  ${Object.keys(values).length} value(s)`);
        st.inserted++; st.cells += Object.keys(values).length;
      }
    }

    console.log(`\n  ${file}`);
    console.log(`     read ${st.read} · blank(skipped) ${st.blank} · invalid ${st.invalid} · ` +
      `${APPLY ? "inserted" : "would insert"} ${st.inserted} · ${APPLY ? "filled" : "would fill"} ${st.filled} · unchanged ${st.unchanged} · cells ${st.cells}`);
    for (const k of K) totals[k] += st[k];
  }

  console.log(`\n  ── TOTAL ──`);
  console.log(`  rows read ${totals.read} · blank ${totals.blank} · invalid ${totals.invalid}`);
  console.log(`  ${APPLY ? "inserted" : "would insert"} ${totals.inserted} · ${APPLY ? "filled" : "would fill"} ${totals.filled} · unchanged ${totals.unchanged}`);
  console.log(`  data cells ${APPLY ? "written" : "that would be written"}: ${totals.cells}`);
  if (warnings.length) {
    console.log(`\n  ${warnings.length} warning(s) — these rows LOAD, but the figure is unusual:`);
    for (const w of warnings.slice(0, 60)) console.log(`     ${w}`);
    if (warnings.length > 60) console.log(`     … and ${warnings.length - 60} more`);
  }
  if (problems.length) {
    console.log(`\n  ⚠ ${problems.length} problem(s) — each row was SKIPPED, not forced:`);
    for (const p of problems.slice(0, 80)) console.log(`     ${p}`);
    if (problems.length > 80) console.log(`     … and ${problems.length - 80} more`);
  } else console.log(`\n  no problems.`);
  fs.writeFileSync("_WORKBOOK_LOAD.json", JSON.stringify({ at: new Date().toISOString(), apply: APPLY, dir: DIR, totals, warnings, problems }, null, 1));
  console.log(`\n  detail -> _WORKBOOK_LOAD.json`);
  if (!APPLY) console.log(`  This was a validation pass. Re-run with --apply to write.\n`);
  await prisma.$disconnect();
}
main().catch(async (e) => { console.error(String(e).slice(0, 3000)); await prisma.$disconnect(); process.exit(1); });
